types:
  WOOD: COAL
  LEATHER: LEATHER
  IRON: IRON_INGOT
  GOLD: GOLD_INGOT
  DIAMOND: DIAMOND
  CHAINMAIL: IRON_INGOT
slots:
  SPADE: 1
  AXE: 3
  PICKAXE: 3
  SWORD: 2
  HOE: 2
  HELMET: 5
  CHESTPLATE: 8
  LEGGINGS: 7
  BOOTS: 4
items:
- WOOD_SPADE
- WOOD_AXE
- WOOD_PICKAXE
- WOOD_SWORD
- WOOD_HOE
- IRON_SPADE
- IRON_AXE
- IRON_PICKAXE
- IRON_SWORD
- IRON_HOE
- GOLD_SPADE
- GOLD_AXE
- GOLD_PICKAXE
- GOLD_SWORD
- GOLD_HOE
- DIAMOND_SPADE
- DIAMOND_AXE
- DIAMOND_PICKAXE
- DIAMOND_SWORD
- DIAMOND_HOE
- LEATHER_HELMET
- LEATHER_CHESTPLATE
- LEATHER_LEGGINGS
- LEATHER_BOOTS
- CHAINMAIL_HELMET
- CHAINMAIL_CHESTPLATE
- CHAINMAIL_LEGGINGS
- CHAINMAIL_BOOTS
- IRON_HELMET
- IRON_CHESTPLATE
- IRON_LEGGINGS
- IRON_BOOTS
- GOLD_HELMET
- GOLD_CHESTPLATE
- GOLD_LEGGINGS
- GOLD_BOOTS
- DIAMOND_HELMET
- DIAMOND_CHESTPLATE
- DIAMOND_LEGGINGS
- DIAMOND_BOOTS